cvp_configlets: {}
cvp_topology:
  ATD_FABRIC:
    devices: []
    parent_container: Tenant
  ATD_LEAFS:
    devices: []
    parent_container: ATD_FABRIC
  ATD_SPINES:
    devices:
    - s1-spine1
    - s1-spine2
    parent_container: ATD_FABRIC
  pod1:
    devices:
    - s1-leaf1
    - s1-leaf2
    parent_container: ATD_LEAFS
  pod2:
    devices:
    - s1-leaf4
    - s1-leaf3
    parent_container: ATD_LEAFS
