---
- name: Manage Arista EOS EVPN/VXLAN Configuration
  hosts: ATD_FABRIC
  connection: local
  gather_facts: false
  collections:
    - arista.avd
  vars:
    fabric_dir_name: "{{ fabric_name }}"

  pre_tasks:

    - name: Retrieve a repository from a distant location and make it available to the local EE
      ansible.scm.git_retrieve:
        origin:
          url: "https://github.com/andubiel/atd-avd.git"
        parent_directory: /tmp/
        branch:
          name: aap-demo
          duplicate_detection: no
      register: repository
      delegate_to: localhost
      run_once: true
    
  tasks:

    - name: Generate intended variables
      import_role:
        name: eos_designs

    - name: Generate device intended config and documentation
      import_role:
        name: eos_cli_config_gen

    - name: Publish the changes
      ansible.scm.git_publish:
        path: "{{ repository['path'] }}"
        token: "{{ password }}"
        user:
          name: "{{ username }}"
          email: "{{ email }}"
      delegate_to: localhost
      run_once: true


    - name: Provision CV with AVD configuration
      import_role:
        name: cv_deploy
      vars:
        cv_server: https://tony-dubiel-redhat-1-6ae85504-eos.topo.testdrive-dev.arista.com
        cv_token: "{{ lab_token }}"
        cv_run_change_control: true
 

    