---
- name: Certify BGP resilency on a link failure
  hosts: ATD_LAB
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
    - arista.eos
  tasks:
    - name: BGP link resilency certification test
      block:
        - name: Backup fabric and host configurations prior to destructive tests
          arista.eos.eos_command:
            commands:
              - copy running-config flash:backup.cfg
          tags: [ setup ]

        - name: Delete test results (if they already exist)
          ansible.builtin.shell: "rm atd-inventory/reports/test_results/*"
          tags: [ setup ]
          run_once: true
        
        - name: Remove certification results directories if they already exist
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          loop:
            - "atd-inventory/certification/bgp/pre_validate"
            - "atd-inventory/certification/bgp/step_1"
            - "atd-inventory/certification/bgp/post_validate"
          tags: [ setup ]
          run_once: true

        - name: Create certification results directories
          ansible.builtin.file:
            path: "{{ item }}"
            state: directory
          loop:
            - "atd-inventory/certification/bgp/pre_validate"
            - "atd-inventory/certification/bgp/step_1"
            - "atd-inventory/certification/bgp/post_validate"
          tags: [ setup ]
          run_once: true

        - name: Baseline fabrics current state using ANTA NRFU catalog
          import_role:
            name: arista.avd.eos_validate_state
          vars:
            use_anta: true
            save_catalog: true
          when: inventory_hostname in groups['ATD_FABRIC']
          tags: [ baseline ]

        - name: Move baseline results to pre-validation folder
          ansible.builtin.shell: "mv atd-inventory/reports/test_results/* atd-inventory/certification/bgp/pre_validate/."
          tags: [ baseline ]
          run_once: true

        # fix assert
        #
        # adding chars when inputted
        # unable to translate to json
        # need to find a solution so can query and assert against data
        # - name: Read output of ANTA tests and assign a variable to them
        #   ansible.builtin.set_fact:
        #     "{{ inventory_hostname | replace('-','_') }}_fact": "{{ lookup('file','/home/coder/project/labfiles/atd-avd/atd-inventory/reports/test_results/{{ inventory_hostname }}-results.json') | to_yaml }}"
        #   when: inventory_hostname in groups['ATD_FABRIC']

        # - debug: var={{ inventory_hostname | replace('-','_') }}_fact
        #   when: inventory_hostname in groups['ATD_FABRIC']

        - name: Disable uplinks on s1-leaf1 to test BGP resilency
          arista.eos.eos_command:
            commands:
              - configure
              - interface ethernet2
              - shutdown
              - interface ethernet3
              - shutdown
          when: "'s1-leaf1' in inventory_hostname"
          tags: [ step1_setup ]

        - name: Validate data-plane between s1-host1 and s1-host2
          import_role:
            name: eos_validate_state
          # async: 300
          # poll: 0
          when: "'s1-leaf1' in inventory_hostname"
          vars:
            use_anta: true
            save_catalog: true

        - name: Validate control-plane on s1-leaf1
          import_role:
            name: eos_validate_state
          when: inventory_hostname in groups['ATD_HOSTS']
          vars:
            use_anta: true
            save_catalog: true

        - name: collect plain-text evidence for reporting
          arista.eos.eos_command:
            commands: 
              - ping 10.1.10.12 source 10.1.10.11 repeat 5
          register: ping_evidence
          when: "'s1-host1' in inventory_hostname"

        - debug: var=ping_evidence
          when: "'s1-host1' in inventory_hostname"

        - name: collect plain-text evidence for reporting
          arista.eos.eos_command:
            commands: 
              - show ip bgp summary
              - show bgp evpn summary
              - show ip interface brief
          register: bgp_evidence
          when: "'s1-leaf1' in inventory_hostname"

        - debug: var=bgp_evidence
          when: "'s1-leaf1' in inventory_hostname"

      always:
        - name: Restore backup fabric and host configuration after destructive tests
          arista.eos.eos_config:
            lines: configure replace flash:backup.cfg 

        - name: Baseline restored fabrics using ANTA NRFU catalog
          import_role:
            name: eos_validate_state
          vars:
            use_anta: true
            save_catalog: true
          when: inventory_hostname in groups['ATD_FABRIC']

        # - name: Use data from certification test to write a report
