---
- name: Certify BGP resilency on a link failure
  hosts: ATD_LAB
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  tasks:
    - name: BGP link resilency certification test
      block:
        - name: Backup fabric and host configurations prior to destructive tests
          arista.eos.eos_config:
            lines: copy running-config flash:backup.cfg

        - name: Baseline fabrics current state using ANTA NRFU catalog
          import_role:
            name: eos_validate_state
          vars:
            use_anta: true
            save_catalog: true
            hosts: ATD_FABRIC

      always:
        - name: Restore backup fabric and host configuration after destructive tests
          arista.eos.eos_config:
            lines: configure replace flash:backup.cfg 