---
- name: Gather gather_facts
  hosts: tony-dubiel-redhat-1-6ae85504-eos.topo.testdrive-dev.arista.com/ssh/host/192.168.0.12
  #connection: local
  vars:
   ansible_user: arista 
   ansible_password: aristaf721
   ansible_network_os: arista.eos.eos
   ansible_connection: network_cli

  tasks:

  - name: Gather facts 
    arista.eos.facts:
    