---
- name: Certify BGP resilency on a link failure
  hosts: ATD_LAB
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  tasks:
    - name: BGP link resilency certification test
      block:
        - name: Backup fabric and host configurations prior to destructive tests
          arista.eos.eos_config:
            lines: copy running-config flash:backup.cfg

        # Need to fail task if test cases fail
        # Cert tests should not start if baseline is incorrect
        # use json_query combined with assert statement
        - name: Baseline fabrics current state using ANTA NRFU catalog
          import_role:
            name: eos_validate_state
          when: inventory_hostname in groups['ATD_FABRIC']
          vars:
            use_anta: true
            save_catalog: true
            hosts: ATD_FABRIC

        - name: Read results from fabric baseline tests
          ansible.builtin.include_vars:
            dir: atd-inventory/reports/test_results
            extensions:
              - 'yml'

        # connectivity test failing (10.1.10.11 to 10.1.10.12)
        #   s1-host1#ping 10.1.10.12 source 10.1.10.11
        #   ping: bind: Permission denied
        #   works without source keywork but this is required in anta
        # need to save these files to a different output dir
        # skip tests that are needed in this 
        # should i copy custom catalog before this step so it doesn't get run in baseline or have a separate test catalog dir for this step?
        - name: Start a continious ping to validate data-plane between s1-host1 and s1-host2
          import_role:
            name: eos_validate_state
          async: 300
          poll: 0
          when: inventory_hostname == "s1-host1"
          vars:
            use_anta: true
            save_catalog: true
            # custom_anta_catalogs_dir: atd-inventory
            # custom_anta_catalogs: custom_anta_catalogs

      always:
        - name: Restore backup fabric and host configuration after destructive tests
          arista.eos.eos_config:
            lines: configure replace flash:backup.cfg 

        - name: Baseline restored fabrics using ANTA NRFU catalog
          import_role:
            name: eos_validate_state
          when: inventory_hostname in groups['ATD_FABRIC']
          vars:
            use_anta: true
            save_catalog: true
            hosts: ATD_FABRIC
        
        # reporting task
