---
- name: Manage Arista EOS EVPN/VXLAN Configuration
  hosts: ATD_FABRIC
  connection: local
  gather_facts: false
  collections:
    - arista.avd
  vars:
    fabric_dir_name: "{{fabric_name}}"
    execute_tasks: false
  tasks:

    - name: Retrieve a repository from a distant location and make it available to the local EE
      ansible.scm.git_retrieve:
        origin:
          url: "https://github.com/andubiel/atd-avd.git"
        parent_directory: /tmp/
        branch:
          name: master
          duplicate_detection: no
      register: repository
      delegate_to: localhost
      run_once: true

    - name: Generate intended variables
      include_role:
        name: eos_designs

    - name: Generate device intended config and documentation
      include_role:
        name: eos_cli_config_gen
    
    - ansible.builtin.file:
         path: /tmp/atd-avd/atd-inventory/intended/structured_configs/
         state: absent
         mode: '0755'
      delegate_to: localhost
      run_once: true

    - name: copy
      ansible.builtin.copy:
        dest: /tmp/atd-avd/atd-inventory/intended/structured_configs/
        src: /runner/inventory/intended/structured_configs
        force: true
      delegate_to: localhost
      run_once: true

    - ansible.builtin.command: ls /runner/inventory/intended/structured_configs
      register: structured
      delegate_to: localhost
      run_once: true

    - debug:
        var: structured
        
    - name: Publish the changes
      ansible.scm.git_publish:
        path: "{{ repository['path'] }}"
        token: "{{ password }}"
        user:
          name: "{{ username }}"
          email: "{{ email }}"
      delegate_to: localhost
      run_once: true