- name: Configuration deployment with CVP
  hosts: cv_servers
  connection: local
  gather_facts: false
  collections:
    - arista.avd
  tasks:
    - name: Retrieve a repository from a distant location and make it available to the local EE
      ansible.scm.git_retrieve:
        origin:
          url: "https://github.com/andubiel/atd-avd.git"
        parent_directory: /tmp/
        branch:
          name: master
          duplicate_detection: no
      register: repository
      delegate_to: localhost
      run_once: true

    - name: Provision CVP with AVD configuration
      include_role:
        name: eos_config_deploy_cvp
      vars:
        container_root: 'ATD_FABRIC'
        configlets_prefix: 'AVD'
        state: present

    - ansible.builtin.file:
         path: /tmp/atd-avd/atd-inventory/intended/structured_configs/cvp
         state: absent
      delegate_to: localhost
      run_once: true
 
    - name: Publish the changes
      ansible.scm.git_publish:
        path: "{{ repository['path'] }}"
        token: "{{ password }}"
        user:
          name: "{{ username }}"
          email: "{{ email }}"
      delegate_to: localhost
      run_once: true

    - name: Retrieve a repository from a distant location and make it available to the local EE
      ansible.scm.git_retrieve:
        origin:
          url: "https://github.com/andubiel/atd-avd.git"
        parent_directory: /tmp/
        branch:
          name: master
          duplicate_detection: no
      register: repository
      delegate_to: localhost
      run_once: true

    

    - name: copy
      ansible.builtin.copy:
        dest: /tmp/atd-avd/atd-inventory/intended/structured_configs/
        src: /runner/inventory/intended/structured_configs/cvp
        force: true
      delegate_to: localhost
      run_once: true
  
    - name: Publish the changes
      ansible.scm.git_publish:
        path: "{{ repository['path'] }}"
        token: "{{ password }}"
        user:
          name: "{{ username }}"
          email: "{{ email }}"
      delegate_to: localhost
      run_once: true
